### ISSUE TITLE
Compress images of the spectro docs

### ISSUE THREAD

**Issue by opatiny** [Hackuarium/docs.hackuarium.org#4]

**Comment by lpatiny** [comment]
In order to resize all the images to a maximum size of 1600 (in any direction) you can use this ImageMagick utility (`mogrify`):

`find docs -execdir sh -c "mogrify -resize '1600x1600>' *.JPG" {} \;`

This will only resize the images larger than 1600.

@andrescvargasr I also resized the bioreactor images but better to do this before uploading because the images are now permanently in the history of the documentation and the repository is now huge (2.5G). Actually it is really to big and we may have to remove I don't know how some part of the history.
